apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: poc-ai-relay
  labels:
    app: web
    autopoc.io/project: ai-relay
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - port: 3000
      targetPort: 3000
